global:
  scrape_interval: 10s
scrape_configs:
 - job_name: kafka
   static_configs:
    - targets:
       - broker:7071
 - job_name: client
   static_configs:
    - targets:
       - producer-consumer:7074