global:
  scrape_interval: 10s
scrape_configs:
  - job_name: kafka
    static_configs:
      - targets:
          - broker:7071
  - job_name: client
    static_configs:
      - targets:
          - producer-consumer:7074
  - job_name: kafka-lag-exporter
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - "kafka-lag-exporter:8000"
        labels:
          namespace: "docker"
          cluster_name: "local"
